#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get -y install haproxy=1.5.\*
echo "backend web-backend
balance roundrobin
server 800-web-01  3.236.65.110check
server 800-web-02 44.192.48.64	 check
frontend http
bind *:80
mode http
default_backend web-backend
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
