#!/usr/bin/env bash

SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
