#!/usr/bin/env bash

# Create the file /var/run/holbertonscript.pid containing its PID
sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'

# Set up signal handlers
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT

# Display 'To infinity and beyond' indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done
