#!/usr/bin/env bash

PID_FILE="/var/run/myscript.pid"

# Create the file /var/run/myscript.pid containing its PID
echo $$ | sudo tee "$PID_FILE"

# Set up signal handlers
trap 'echo "I hate the kill command"; rm "$PID_FILE"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$PID_FILE"; exit' SIGQUIT

# Display 'To infinity and beyond' indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done

