#!/bin/bash

SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already running."
        else
            $SCRIPT &
            echo "$!" > $PID_FILE
            echo "manage_my_process started"
        fi
        ;;

    stop)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat $PID_FILE)
            kill $PID
            rm $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;

    restart)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat $PID_FILE)
            kill $PID
            rm $PID_FILE
            echo "manage_my_process stopped"
        fi
        $SCRIPT &
        echo "$!" > $PID_FILE
        echo "manage_my_process restarted"
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
