#!/usr/bin/env bash
# while and if statement

COUNTER=0
while [ $COUNTER -ne 11 ]
do
    if [ $COUNTER -eq 9 ];then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER++))
done
