#!/usr/bin/env bash
# Displays numbers from 1 to 20 with superstitions.

COUNTER=1
while [ $COUNTER -le 20 ]
do
    echo "$COUNTER"
    
    case $COUNTER in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    
    ((COUNTER++))
done
