#!/usr/bin/env bash
# Gives information about the school file.

FILE="school"

if [ -e "$FILE" ]; then
    echo "school file exists"

    if [ ! -s "$FILE" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"

        if [ -f "$FILE" ]; then
            echo "school is a regular file"
        fi
    fi
else
    echo "school file does not exist"
fi
